### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by soloam** [tomarc3/node-red-contrib-lametric-notification#3]
Hello, this i not a issue, but an idea, allow passing the values of the fields (like icon and alarm) by message, so that the display could be more dynamic.

Thank You

**Comment by tomarc3** [comment]
Hi,
Thank you for the input. I'm not sure if I get your idea right: If I start extending the message to pass the fields as message parameters I'll end up with a structure like the one specified in the Notification API: https://lametric-documentation.readthedocs.io/en/latest/reference-docs/device-notifications.html#body
But then then there is no need for a proper LaMetric Notification node, as you can do the same thing with a generic http request node.
The intension of the LaMetric Notification node is to have a simple way to send a notification to a LaMetic device without having to compose a complicated message in beforehand. 
What would be a use case where you need a more dynamic interface?
Br Tom

**Comment by Bierchermuesli** [comment]
The properties e.g. msg.icon can override the values in the form. It should be Optional - basic users can still use the form. 

In my case I send multiple Messages after the other with **one**  Lametric Node - here it would be nice to set override icon by msg.icon. Otherwise I have to multiply the Lametric node (where the API key gets lost...)
